### ISSUE TITLE
sse for fiber

### ISSUE THREAD

**Issue by bashery** [amalshaji/awesome-fiber#1]
Fiber need sever sent event  plugin.
can you create one for fiber ?!
Thanks.

**Comment by amalshaji** [comment]
Oh! I just started a collection of resources on Fiber. Also I'm not familiar with SSE.

**Comment by bashery** [comment]
I suggested the idea to the Fiber team and community.
It seems that this is not a priority.
I had to divide my project into two parts, split my build on Fiber and one on Echo because most libraries are compatible with the standard library and not fasthttp.
I'm thinking about making an sse plugin for Fiber. I hope I have time.

**Comment by amalshaji** [comment]
Great. Maybe you could port [this](https://github.com/julienschmidt/sse) to Fiber.
